"""
Module purpose:
- Public package entrypoint for backend game systems.

This file re-exports symbols from `map_system` so callers can use:
- from backend import GameEngine, CommandPipeline, PlayerRole, GlobalConfig, ...
"""

from .map_system import (
    BASE_HOLY_WATER_PER_TIME,
    MOVE_TIME_COST,
    PHASE_BATTLE,
    PHASE_EMERGENCY,
    AttackPreference,
    CampusMap,
    CharacterProfile,
    CharacterStatus,
    CompanionProfile,
    CompanionRoleType,
    CommandPipeline,
    DeployedUnit,
    GeminiClient,
    GameEngine,
    GlobalEventChecker,
    GlobalConfig,
    GlobalStorySetting,
    LLMAgentBridge,
    MapNode,
    MovementTask,
    NearbyUnitStatus,
    PlayerRole,
    QueueMessage,
    Role,
    TriggerState,
    TargetKind,
    UnitCard,
    UnitClass,
    build_lazy_npc_prompt,
    build_narrative_prompt,
    build_step_context,
    build_world_base_setting,
    build_all_unit_cards,
    build_default_campus_map,
    build_default_companion_profiles,
    build_default_character_profiles,
    build_default_story_setting,
    build_default_unit_cards,
    get_scene_paragraph,
)

__all__ = [
    "AttackPreference",
    "BASE_HOLY_WATER_PER_TIME",
    "CampusMap",
    "CharacterProfile",
    "CharacterStatus",
    "CompanionProfile",
    "CompanionRoleType",
    "CommandPipeline",
    "DeployedUnit",
    "GeminiClient",
    "GameEngine",
    "GlobalEventChecker",
    "GlobalConfig",
    "GlobalStorySetting",
    "LLMAgentBridge",
    "MapNode",
    "MOVE_TIME_COST",
    "MovementTask",
    "NearbyUnitStatus",
    "PHASE_BATTLE",
    "PHASE_EMERGENCY",
    "PlayerRole",
    "QueueMessage",
    "Role",
    "build_lazy_npc_prompt",
    "build_narrative_prompt",
    "build_step_context",
    "build_world_base_setting",
    "TriggerState",
    "TargetKind",
    "UnitCard",
    "UnitClass",
    "build_all_unit_cards",
    "build_default_campus_map",
    "build_default_companion_profiles",
    "build_default_character_profiles",
    "build_default_story_setting",
    "build_default_unit_cards",
    "get_scene_paragraph",
]
